### ISSUE TITLE
Cant start my minecraft server because of this error

### ISSUE THREAD

**Issue by FrxstY123** [fzzyhmstrs/ai#103]
[01:36:20] [main/ERROR]: Failed to start the minecraft server
111 | java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'amethyst_imbuement'!
112 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
113 | at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
114 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
115 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
116 | at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
117 | at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
118 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
119 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
120 | at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
121 | at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
122 | at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[server.jar:0.11.2]
123 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
124 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
125 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
126 | at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
127 | at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:27) ~[rust-extension-1.0.10.jar:?]
128 | Caused by: java.lang.NoClassDefFoundError: dev/emi/trinkets/api/event/TrinketDropCallback
129 | at me.fzzyhmstrs.amethyst_imbuement.augment.SoulbindingAugment.<init>(SoulbindingAugment.kt:43) ~[amethyst_imbuement-1.20.1-03.jar:?]
130 | at me.fzzyhmstrs.amethyst_imbuement.registry.RegisterEnchantment.<clinit>(RegisterEnchantment.kt:65) ~[amethyst_imbuement-1.20.1-03.jar:?]
131 | at me.fzzyhmstrs.amethyst_imbuement.AI.onInitialize(amethyst_imbuement.kt:31) ~[amethyst_imbuement-1.20.1-03.jar:?]
132 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
133 | ... 13 more
134 | Caused by: java.lang.ClassNotFoundException: dev.emi.trinkets.api.event.TrinketDropCallback
135 | at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
136 | at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
137 | at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
138 | at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
139 | at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
140 | at me.fzzyhmstrs.amethyst_imbuement.augment.SoulbindingAugment.<init>(SoulbindingAugment.kt:43) ~[amethyst_imbuement-1.20.1-03.jar:?]
141 | at me.fzzyhmstrs.amethyst_imbuement.registry.RegisterEnchantment.<clinit>(RegisterEnchantment.kt:65) ~[amethyst_imbuement-1.20.1-03.jar:?]
142 | at me.fzzyhmstrs.amethyst_imbuement.AI.onInitialize(amethyst_imbuement.kt:31) ~[amethyst_imbuement-1.20.1-03.jar:?]
143 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
144 | ... 13 more
145

<br class="Apple-interchange-newline">
</body>
</html>[01:36:20] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'amethyst_imbuement'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
	at net.minecraft.server.Main.main(Main.java:[112](https://mclo.gs/9u4LyR4#L112)) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[server.jar:0.11.2]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:27) ~[rust-extension-1.0.10.jar:?]
Caused by: java.lang.NoClassDefFoundError: dev/emi/trinkets/api/event/TrinketDropCallback
	at me.fzzyhmstrs.amethyst_imbuement.augment.SoulbindingAugment.<init>(SoulbindingAugment.kt:43) ~[amethyst_imbuement-1.20.1-03.jar:?]
	at me.fzzyhmstrs.amethyst_imbuement.registry.RegisterEnchantment.<clinit>(RegisterEnchantment.kt:65) ~[amethyst_imbuement-1.20.1-03.jar:?]
	at me.fzzyhmstrs.amethyst_imbuement.AI.onInitialize(amethyst_imbuement.kt:31) ~[amethyst_imbuement-1.20.1-03.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	... 13 more
Caused by: java.lang.ClassNotFoundException: dev.emi.trinkets.api.event.TrinketDropCallback
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at me.fzzyhmstrs.amethyst_imbuement.augment.SoulbindingAugment.<init>(SoulbindingAugment.kt:43) ~[amethyst_imbuement-1.20.1-03.jar:?]
	at me.fzzyhmstrs.amethyst_imbuement.registry.RegisterEnchantment.<clinit>(RegisterEnchantment.kt:65) ~[amethyst_imbuement-1.20.1-03.jar:?]
	at me.fzzyhmstrs.amethyst_imbuement.AI.onInitialize(amethyst_imbuement.kt:31) ~[amethyst_imbuement-1.20.1-03.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	... 13 more

**Comment by fzzyhmstrs** [comment]
If you don't have Trinkets installed, install that and try again.
