### ISSUE TITLE
Imbuing Table causing a crash when items are put in

### ISSUE THREAD

**Issue by twaalfkraaien** [fzzyhmstrs/ai#104]
Whenever a item is put into the imbument table, if its correct or not it causes the game to completely crash.

```Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/class_746
	at github.pitbox46.itemblacklist.utils.Utils.getPlayer(Utils.java:55)
	at net.minecraft.class_1703.handler$dgo000$itemblacklist$onDetectAndSendChanges(class_1703.java:1395)
	at net.minecraft.class_1703.method_7623(class_1703.java)
	at me.fzzyhmstrs.amethyst_imbuement.screen.ImbuingTableScreenHandler.method_7609(ImbuingTableScreenHandler.kt:324)
	at me.fzzyhmstrs.amethyst_imbuement.screen.ImbuingTableScreenHandler.onParentChanged(ImbuingTableScreenHandler.kt:84)
	at me.fzzyhmstrs.amethyst_imbuement.screen.ImbuingTableScreenHandler.access$onParentChanged(ImbuingTableScreenHandler.kt:64)
	at me.fzzyhmstrs.amethyst_imbuement.screen.ImbuingTableScreenHandler$listener$1.invoke(ImbuingTableScreenHandler.kt:97)
	at me.fzzyhmstrs.amethyst_imbuement.screen.ImbuingTableScreenHandler$listener$1.invoke(ImbuingTableScreenHandler.kt:97)
	at me.fzzyhmstrs.amethyst_imbuement.screen.ImbuingTableScreenHandler._init_$lambda-0(ImbuingTableScreenHandler.kt:136)
	at net.minecraft.class_1277.method_5431(class_1277.java:162)
	at me.fzzyhmstrs.amethyst_imbuement.entity.ImbuingTableBlockEntity$ImbuingInventory.method_5431(ImbuingTableBlockEntity.kt:169)
	at net.minecraft.class_1277.redirect$dak000$fabric-transfer-api-v1$fabric_redirectMarkDirty(class_1277.java:1043)
	at net.minecraft.class_1277.method_5447(class_1277.java:140)
	at net.minecraft.class_1735.method_7673(class_1735.java:61)
	at me.fzzyhmstrs.amethyst_imbuement.screen.ImbuingTableScreenHandler$ImbuingSlot.method_7673(ImbuingTableScreenHandler.kt:684)
	at net.minecraft.class_1735.method_32755(class_1735.java:151)
	at net.minecraft.class_1703.method_30010(class_1703.java:414)
	at net.minecraft.class_1703.method_7593(class_1703.java:293)
	at net.minecraft.class_3244.method_12076(class_3244.java:1770)
	at net.minecraft.class_2813.method_12191(class_2813.java:58)
	at net.minecraft.class_2813.method_11054(class_2813.java:13)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_5383(class_1255.java:116)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 35 more```

**Comment by fzzyhmstrs** [comment]
This seems to actually be caused by "item blacklist":
![image](https://github.com/fzzyhmstrs/ai/assets/72876796/514f4bc3-6ceb-4467-9e5c-862a399fa62e)
