### ISSUE TITLE
something error 

### ISSUE THREAD

**Issue by DoubleAxeray** [fzzyhmstrs/ai#118]
![image](https://github.com/fzzyhmstrs/ai/assets/143949089/12505b02-1c3d-4e05-bc0a-1b48ed7c61de)

—————————————log———————————————

00:44:35] [Render thread/ERROR]: Error loading and compiling book amethyst_imbuement:glistering_tome, using empty contents
java.lang.RuntimeException: Error building entry amethyst_imbuement:trinket_totem_augments/hasting
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:97) ~[%5B帕秋莉手册%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
	at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
	at vazkii.patchouli.client.book.BookContentsBuilder.build(BookContentsBuilder.java:93) ~[%5B帕秋莉手册%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.client.book.BookContentsBuilder.loadAndBuildFor(BookContentsBuilder.java:73) ~[%5B帕秋莉手册%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:194) ~[%5B帕秋莉手册%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:99) ~[%5B帕秋莉手册%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:63) ~[%5B帕秋莉手册%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.client.base.ClientAdvancements.onClientPacket(ClientAdvancements.java:34) ~[%5B帕秋莉手册%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
	at net.minecraft.class_632.handler$gcd000$patchouli$onSync(class_632.java:1517) ~[client-intermediary.jar:?]
	at net.minecraft.class_632.method_2861(class_632.java:67) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11130(class_634.java:1404) ~[client-intermediary.jar:?]
	at net.minecraft.class_2779.method_11925(class_2779.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_2779.method_11054(class_2779.java:16) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[test.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
Caused by: java.lang.RuntimeException: Error while loading entry amethyst_imbuement:trinket_totem_augments/hasting page 1
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:241) ~[%5B帕秋莉手册%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:95) ~[%5B帕秋莉手册%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
	... 23 more
Caused by: java.lang.RuntimeException: Unknown item ID: minecraft:amethyst_imbuement
	at vazkii.patchouli.common.util.ItemStackUtil.loadFromParsed(ItemStackUtil.java:77) ~[%5B帕秋莉手册%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.common.util.ItemStackUtil.loadStackFromString(ItemStackUtil.java:89) ~[%5B帕秋莉手册%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.common.util.ItemStackUtil.loadStackListFromString(ItemStackUtil.java:104) ~[%5B帕秋莉手册%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.client.book.template.variable.ItemStackArrayVariableSerializer.fromNonArray(ItemStackArrayVariableSerializer.java:37) ~[%5B帕秋莉手册%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.client.book.template.variable.ItemStackArrayVariableSerializer.fromJson(ItemStackArrayVariableSerializer.java:29) ~[%5B帕秋莉手册%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.client.book.template.variable.ItemStackArrayVariableSerializer.fromJson(ItemStackArrayVariableSerializer.java:14) ~[%5B帕秋莉手册%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.client.book.template.variable.Variable.as(Variable.java:31) ~[%5B帕秋莉手册%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.client.book.template.component.ComponentItemStack.onVariablesAvailable(ComponentItemStack.java:38) ~[%5B帕秋莉手册%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.client.book.template.VariableAssigner.assignVariableHolders(VariableAssigner.java:49) ~[%5B帕秋莉手册%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.client.book.template.TemplateComponent.compile(TemplateComponent.java:52) ~[%5B帕秋莉手册%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.client.book.template.BookTemplate.compile(BookTemplate.java:115) ~[%5B帕秋莉手册%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.client.book.page.PageTemplate.build(PageTemplate.java:29) ~[%5B帕秋莉手册%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:238) ~[%5B帕秋莉手册%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:95) ~[%5B帕秋莉手册%5D%20Patchouli-1.20.1-81-FABRIC.jar:?]
	... 23 more

**Comment by DoubleAxeray** [comment]
This item has not been translated correctly into Chinese.
![image](https://github.com/fzzyhmstrs/ai/assets/143949089/9ca97295-299d-4394-ad44-255fdfd2b451)
This item is missing the correct translation into Chinese, and there is no description or icon for this effect
![image](https://github.com/fzzyhmstrs/ai/assets/143949089/d89064d7-4c94-4c55-9a02-d98ecc7ee85f)

**Comment by DoubleAxeray** [comment]
This also causes an error in another mod, [repurposed_structures]
—————————————log———————————————
[00:44:14] [Server thread/ERROR]: (Repurposed Structures POOL MERGER) Found an entry in repurposed_structures:villages/swamp/houses that points to the non-existent nbt file called amethyst_imbuement:village/swamp_rs_crystal_workshop

**Comment by fzzyhmstrs** [comment]
The two errors are unrelated. If you are using an older version of minecraft (before 1.20), the chinese language book has errors I haven't ported back from the 1.20.1 version. This newest addition is related to structures and has nothing to do with patchouli , but thank you for pointing it out to me.

**Comment by DoubleAxeray** [comment]
> The two errors are unrelated. If you are using an older version of minecraft (before 1.20), the chinese language book has errors I haven't ported back from the 1.20.1 version. This newest addition is related to structures and has nothing to do with patchouli , but thank you for pointing it out to me.

I am using version 1.20.1
fabric：0.14.22
