### ISSUE TITLE
Book of Lore and Mythos crashing game when opened

### ISSUE THREAD

**Issue by rcolabuno** [fzzyhmstrs/ai#137]
I've been making a 1.20.1 modpack to play with my friends, and i absolutely love this mod, however whenever I attempt to open and activate a book of lore or a book of mythos the game immediately crashes, i tried isolating the mod to see if it was an incompatibility and it wasn't, but I'm not super good at reading crash reports so i could be missing something? i have the crash reports of what the game says happens 

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-01-31 21:41:59
Description: Unexpected error

java.lang.NoSuchMethodError: 'net.minecraft.class_6862 me.fzzyhmstrs.amethyst_core.scepter_util.augments.ScepterAugment.getTag()'
	at me.fzzyhmstrs.amethyst_imbuement.util.ImbuingRecipe.centerSlotGenerator(ImbuingRecipe.kt:218)
	at me.fzzyhmstrs.amethyst_imbuement.util.ImbuingRecipe.access$centerSlotGenerator(ImbuingRecipe.kt:32)
	at me.fzzyhmstrs.amethyst_imbuement.util.ImbuingRecipe$centerSlot$2.invoke(ImbuingRecipe.kt:47)
	at me.fzzyhmstrs.amethyst_imbuement.util.ImbuingRecipe$centerSlot$2.invoke(ImbuingRecipe.kt:46)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at me.fzzyhmstrs.amethyst_imbuement.util.ImbuingRecipe.getCenterSlot(ImbuingRecipe.kt:46)
	at me.fzzyhmstrs.amethyst_imbuement.util.ImbuingRecipe.getCenterIngredient(ImbuingRecipe.kt:205)
	at me.fzzyhmstrs.amethyst_imbuement.util.RecipeUtil.buildInputProviders$amethyst_imbuement(RecipeUtil.kt:107)
	at me.fzzyhmstrs.amethyst_imbuement.screen.KnowledgeBookScreen.method_25426(KnowledgeBookScreen.kt:73)
	at net.minecraft.class_437.method_25423(class_437.java:297)
	at net.minecraft.class_310.method_1507(class_310.java:1080)
	at me.fzzyhmstrs.amethyst_imbuement.item.book.BookOfMythosItem.useAfterWriting(BookOfMythosItem.kt:49)
	at me.fzzyhmstrs.amethyst_core.item_util.AbstractAugmentBookItem.method_7836(AbstractAugmentBookItem.kt:155)
	at net.minecraft.class_1799.method_7913(class_1799.java:284)
	at net.minecraft.class_636.method_41929(class_636.java:387)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2919(class_636.java:379)
	at net.minecraft.class_310.method_1583(class_310.java:1822)
	at net.minecraft.class_310.method_1508(class_310.java:2052)
	at net.minecraft.class_310.method_1574(class_310.java:1883)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.fzzyhmstrs.amethyst_imbuement.util.ImbuingRecipe.centerSlotGenerator(ImbuingRecipe.kt:218)
	at me.fzzyhmstrs.amethyst_imbuement.util.ImbuingRecipe.access$centerSlotGenerator(ImbuingRecipe.kt:32)
	at me.fzzyhmstrs.amethyst_imbuement.util.ImbuingRecipe$centerSlot$2.invoke(ImbuingRecipe.kt:47)
	at me.fzzyhmstrs.amethyst_imbuement.util.ImbuingRecipe$centerSlot$2.invoke(ImbuingRecipe.kt:46)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at me.fzzyhmstrs.amethyst_imbuement.util.ImbuingRecipe.getCenterSlot(ImbuingRecipe.kt:46)
	at me.fzzyhmstrs.amethyst_imbuement.util.ImbuingRecipe.getCenterIngredient(ImbuingRecipe.kt:205)
	at me.fzzyhmstrs.amethyst_imbuement.util.RecipeUtil.buildInputProviders$amethyst_imbuement(RecipeUtil.kt:107)
	at me.fzzyhmstrs.amethyst_imbuement.screen.KnowledgeBookScreen.method_25426(KnowledgeBookScreen.kt:73)
	at net.minecraft.class_437.method_25423(class_437.java:297)
	at net.minecraft.class_310.method_1507(class_310.java:1080)
	at me.fzzyhmstrs.amethyst_imbuement.item.book.BookOfMythosItem.useAfterWriting(BookOfMythosItem.kt:49)
	at me.fzzyhmstrs.amethyst_core.item_util.AbstractAugmentBookItem.method_7836(AbstractAugmentBookItem.kt:155)
	at net.minecraft.class_1799.method_7913(class_1799.java:284)
	at net.minecraft.class_636.method_41929(class_636.java:387)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2919(class_636.java:379)
	at net.minecraft.class_310.method_1583(class_310.java:1822)
	at net.minecraft.class_310.method_1508(class_310.java:2052)

-- Affected level --
Details:
	All players: 1 total; [class_746['illustryous'/133, l='ClientLevel', x=-8.73, y=70.00, z=-12.26]]
	Chunk stats: 961, 581
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,71,0), Section: (at 0,7,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 15476 game time, 15476 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric

**Comment by Cocomere** [comment]
I'm having the same issue. Even going back a few versions, I keep crashing from this mod.

**Comment by fzzyhmstrs** [comment]
The issue is with Amethyst Core, not Imbuement. Reverting both AI and AC should fix it until I get the COre fix out soon

**Comment by rcolabuno** [comment]
alright ill use a backlog version until then, thank you!

**Comment by fzzyhmstrs** [comment]
Version 1.4.7 of Amethyst Core is out on modrinth and cf and should resolve this issue
