### ISSUE TITLE
Really weird crash

### ISSUE THREAD

**Issue by Sunconure11** [fzzyhmstrs/ai#17]
https://pastebin.com/Wz5wP49w

https://pastebin.com/NcsFZMAa

**Comment by fzzyhmstrs** [comment]
I can't find anything relevant to my mod in the first stacktrace at all. Something that mixes into TexturedRenderLayers is causing that. I don't really have any advice I can give regarding this crash. One of your mods messes around with textures, and does so in a way that crashes.

FOr the second stacktrace, tt looks like there is a mixin conflict between "bamboo combat" and "earthbounds". The stacktrace shows my mod as having a problem because my mod tries to call the class with the conflict ("EnchantmentHelper") and can't because the mixins run into their error and crash. I would follow up with the creators of the two mods mentioned and see if they can resolve things.

Here's the relevant second stacktrace snippet (you can see the mods in question mentioned on lines 1, 9, and 10:
```
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [earthbounds.mixins.json:EnchantmentHelperMixin from mod earthbounds] from phase [DEFAULT] in config [earthbounds.mixins.json] FAILED during APPLY
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
		... 21 more
	Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE_ASSIGN") on 
net/minecraft/class_1890::applyEnchantmentsCorrectly with priority 1000 cannot inject into
 net/minecraft/class_1890::method_8229(ILnet/minecraft/class_1799;Z)Ljava/util/List; merged by 
net.bamboo.combat.mixin.EnchantmentHelperMixin** with priority 1000 [PREINJECT Applicator Phase -> 
earthbounds.mixins.json:EnchantmentHelperMixin from mod earthbounds -> Prepare Injections ->  -> 
handler$eoi000$applyEnchantmentsCorrectly(ILnet/minecraft/class_1799;ZLorg/spongepowered/asm/mixin/injection/callback/
CallbackInfoReturnable;Ljava/util/List;Lnet/minecraft/class_1792;ZLjava/util/Iterator;Lnet/minecraft/class_1887;)V -> Prepare]
```

**Comment by Sunconure11** [comment]
This particular crash has been solved, but it seems another came up.

https://gist.github.com/Sunconure11/6b011f7d14e522a9891158b69dcf52e2

**Comment by fzzyhmstrs** [comment]
The below seems to be the issue, something related to "polymer" not mixing in properly (you can see "polymer" called out in the 4th Caused-By block).

Basically "polymer" crashed the mixin for "class_3244" and then every mod that tried to mixin to that class hit a wall, hence the huge pile of suppressed BootstrapMethod errors. class_3244 is the server network handler, so it's a very common mixin target.

```
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3244 failed
	at net.adventurez.network.KeybindPacket.init(KeybindPacket.java:18)
	at net.adventurez.AdventureMain.onInitialize(AdventureMain.java:16)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 9 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3244 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 12 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 16 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for polymer.mixins.json:compat.immersive_portals.ip_ServerPlayNetworkHandlerMixin from mod polymer during activity: [Transform -> Method polymer_sendRequiredPackets(Lnet/minecraft/class_2596;)Lnet/minecraft/class_2596; -> INVOKESTATIC -> qouteall/imm_ptl/core/network/IPCommonNetwork::withForceRedirect:(Lnet/minecraft/class_3218;Ljava/lang/Runnable;)V]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 19 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: qouteall.imm_ptl.core.network.IPCommonNetwork
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:783)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:769)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:735)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307)
	... 25 more
Caused by: java.lang.ClassNotFoundException: qouteall.imm_ptl.core.network.IPCommonNetwork
	... 29 more
```

**Comment by Patbox** [comment]
Update to latest 1.18 polymer (2.0.0-rc.4.1) manually or downgrade Immersive Portals

**Comment by fzzyhmstrs** [comment]
Marking as closed per input from @Patbox

**Comment by Sunconure11** [comment]
> Update to latest 1.18 polymer (2.0.0-rc.4.1) manually or downgrade Immersive Portals

I was on that version. Strange.
