### ISSUE TITLE
Error in 1.18.1

### ISSUE THREAD

**Issue by KMFrench1** [fzzyhmstrs/ai#18]
1.18.1, only this mod installed. The following error is thrown. You can repeat it but using curseforge app to create a instance. Install only your mod. but below is the error message. 

Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config fabric-api-lookup-api-v1.mixins.json for mod fabric-api-lookup-api-v1
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:95)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:153)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config fabric-api-lookup-api-v1.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:93)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'fabric-api-lookup-api-v1.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 6 more

**Comment by fzzyhmstrs** [comment]
Are the dependencies for the mod installed? The mod doesn't launch standalone; You need at least Fabric API and Fabric Language Kotlin installed.

**Comment by KMFrench1** [comment]
yes, curse forge installs dependencies for you when you install mods. I believe the log shows what mods are installed. I am not at computer at this exact moment but I remember that only 3 jars where in the folder both koltin and fabric, then your mod.

**Comment by fzzyhmstrs** [comment]
That still may be the issue. I just checked, and I didn't actually have the Fabric API (distinct from Fabric itself) listed in my dependencies. I added it in for all three newest versions so it should grab it now if it didn't.

**Comment by KMFrench1** [comment]
I just sat in front of my computer. So I have amethyst_imbuement-1.18.1-17.jar, fabric-api-0.46.6+1.18.jar, fabric-language-kotlin-1.8.1+kotlin.1.7.0.jar.
Those are the only Jars in the mod folder.

**Comment by KMFrench1** [comment]
Also Running Fabric 0.14.8. if that helps

**Comment by KMFrench1** [comment]
That's just stupid. I ran the game to get a fresh log, and it loaded. Which is good, but make me feel dumb. So what ever the error was yesterday, did not happen today. No clue what is going on, Anyway it is working now.

**Comment by fzzyhmstrs** [comment]
Well my favorite kind of issue is a non-issue. Open something back up if you run into problems again!
