### ISSUE TITLE
[1.18.2 fabric]server log error

### ISSUE THREAD

**Issue by Qian-F** [fzzyhmstrs/ai#97]
Failed to handle packet net.minecraft.class_2886@7142644a, suppressing error
java.lang.RuntimeException: Cannot load class me.fzzyhmstrs.amethyst_imbuement.AIClient in environment type SERVER
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at me.fzzyhmstrs.amethyst_imbuement.scepter.SmitingBlowAugment$Companion.generateParticles(SmitingBlowAugment.kt:98) ~[amethyst_imbuement-1.18.2-45.jar:?]
        at me.fzzyhmstrs.amethyst_imbuement.scepter.SmitingBlowAugment$Companion.access$generateParticles(SmitingBlowAugment.kt:84) ~[amethyst_imbuement-1.18.2-45.jar:?]
        at me.fzzyhmstrs.amethyst_imbuement.scepter.SmitingBlowAugment.supportEffect(SmitingBlowAugment.kt:56) ~[amethyst_imbuement-1.18.2-45.jar:?]
        at me.fzzyhmstrs.amethyst_core.scepter_util.augments.MinorSupportAugment.applyTasks(MinorSupportAugment.kt:27) ~[amethyst_core-1.0.4+1.18.2.jar:?]
        at me.fzzyhmstrs.amethyst_core.scepter_util.augments.ScepterAugment.applyModifiableTasks(ScepterAugment.kt:59) ~[amethyst_core-1.0.4+1.18.2.jar:?]
        at me.fzzyhmstrs.amethyst_core.item_util.AugmentScepterItem.serverUse(AugmentScepterItem.kt:135) ~[amethyst_core-1.0.4+1.18.2.jar:?]
        at me.fzzyhmstrs.amethyst_core.item_util.AugmentScepterItem.method_7836(AugmentScepterItem.kt:116) ~[amethyst_core-1.0.4+1.18.2.jar:?]
        at net.minecraft.class_1799.method_7913(class_1799.java:262) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14256(class_3225.java:291) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12065(class_3244.java:1117) ~[server-intermediary.jar:?]
        at net.minecraft.class_2886.method_12550(class_2886.java:25) ~[server-intermediary.jar:?]
        at net.minecraft.class_2886.method_11054(class_2886.java:7) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.redirect$ccn000$c2me-opts-scheduling$redirectExecuteTask(class_1255.java:521) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:15288) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:769) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by fzzyhmstrs** [comment]
Sorry to see that happening, but I no longer support 1.18.x. You could disable Smiting Blow in the configs if you'd like (`config > amethyst_imbuement > augments > SmitingBlowAugment_v1.json`)

**Comment by Qian-F** [comment]
> Sorry to see that happening, but I no longer support 1.18.x. You could disable Smiting Blow in the configs if you'd like (`config > amethyst_imbuement > augments > SmitingBlowAugment_v1.json`)

thank you for your reply!
